language: java

jdk:
- oraclejdk8

script: ./gradlew updateSHAs check assemble

deploy:
  provider: script
  script: ci/ci-deploy.sh
  skip_cleanup: true
  on:
    all_branches: true

env:
- GH_USER_EMAIL=scarduzio+travisci@gmail.com
- GH_USER_NAME=Travis CI

after_success:
- |

       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

       # Decrypt the file containing the private key

       openssl aes-256-cbc \
         -K $encrypted_XXXXXXXXXXXX_key \
         -iv $encrypted_XXXXXXXXXXXX_iv \
         -in ".travis/github_deploy_key.enc" \
         -out "$SSH_FILE" -d

       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

       # Enable SSH authentication

       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config
